sylius_invoicing_invoice:
    resource: |
        alias: sylius_invoicing.invoice
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        only: ['index']
        grid: sylius_invoicing_invoice
        permission: true
        vars:
            all:
                header: sylius_invoicing.ui.invoices
                subheader: sylius_invoicing.ui.manage_invoices
                breadcrumb: sylius_invoicing.ui.invoices
            index:
                icon: inbox
    type: sylius.resource

sylius_invoicing_admin_invoice_show:
    path: /invoices/{id}
    methods: [GET]
    defaults:
        _controller: sylius_invoicing.controller.invoice::showAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/shared/crud/show.html.twig"

sylius_invoicing_admin_invoice_download:
    path: /invoices/{id}/download
    methods: [GET]
    defaults:
        _controller: sylius_invoicing.controller.download_invoice

sylius_invoicing_admin_invoice_resend:
    path: /invoices/{id}/resend
    methods: [GET]
    defaults:
        _controller: sylius_invoicing.controller.resend_invoice
