imports:
    - { resource: '@SyliusInvoicingPlugin/config/twig_hooks/**/*.yaml' }
    - { resource: '@SyliusInvoicingPlugin/config/winzou_state_machine.php' }

parameters:
    sylius_invoicing.invoice_save_path: "%kernel.project_dir%/private/invoices/"
    sylius_invoicing.filesystem_adapter.invoice: "sylius_invoicing_invoice"

sylius_invoicing:
    pdf_generator:
        allowed_files:
            - '%env(default:sylius_invoicing.default_logo_file:resolve:SYLIUS_INVOICING_LOGO_FILE)%'

sylius_mailer:
    emails:
        invoice_generated:
            subject: sylius.emails.invoice_generated.subject
            template: "@SyliusInvoicingPlugin/admin/invoice/email/invoice_generated.html.twig"

knp_snappy:
    pdf:
        enabled: true

sylius_grid:
    templates:
        action:
            download: '@SyliusInvoicingPlugin/admin/shared/action/download.html.twig'
    grids:
        sylius_invoicing_invoice:
            driver:
                name: doctrine/orm
                options:
                    class: '%sylius_invoicing.model.invoice.class%'
            sorting:
                issuedAt: desc
            fields:
                number:
                    type: string
                    label: sylius_invoicing.ui.invoice_number
                    sortable: true
                orderNumber:
                    type: twig
                    label: sylius.ui.order
                    path: order
                    options:
                        template: "@SyliusAdmin/shared/grid/field/order_number.html.twig"
                    sortable: order.number
                channel:
                    type: twig
                    label: sylius.ui.channel
                    options:
                        template: "@SyliusAdmin/shared/grid/field/channel.html.twig"
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    sortable: total
                    options:
                        template: "@SyliusAdmin/order/grid/field/order_total.html.twig"
                issuedAt:
                    type: datetime
                    label: sylius_invoicing.ui.issued_at
                    options:
                        format: 'Y-m-d H:i:s'
                    sortable: true
            filters:
                orderNumber:
                    type: string
                    label: sylius_invoicing.ui.order_number
                    options:
                        fields: [order.number]
                number:
                    type: string
                    label: sylius_invoicing.ui.invoice_number
                issuedAt:
                    type: date
                    label: sylius_invoicing.ui.issued_at
                channel:
                    type: entity
                    label: sylius.ui.channel
                    form_options:
                        class: "%sylius.model.channel.class%"
            actions:
                item:
                    show:
                        type: show
                    download:
                        type: download
                        enabled: '%sylius_invoicing.pdf_generator.enabled%'
                        options:
                            link:
                                route: sylius_invoicing_admin_invoice_download
                                parameters:
                                    id: resource.id
                    resend:
                        type: default
                        label: sylius_invoicing.ui.resend_invoice
                        icon: "tabler:send"
                        options:
                            link:
                                route: sylius_invoicing_admin_invoice_resend
                                parameters:
                                    id: resource.id

        sylius_shop_account_order:
            fields:
                invoices:
                    type: twig
                    label: sylius_invoicing.ui.invoices
                    path: .
                    options:
                        template: "@SyliusInvoicingPlugin/shop/account/order/grid/field/invoices.html.twig"

framework:
    messenger:
        buses:
            sylius.event_bus:
                default_middleware: allow_no_handlers
            sylius.command_bus:
                middleware:
                    - 'validation'
                    - 'doctrine_transaction'

knp_gaufrette:
    adapters:
        sylius_invoicing_invoice:
            local:
                directory: "%sylius_invoicing.invoice_save_path%"
                create: true
    filesystems:
        sylius_invoicing_invoice:
            adapter: "%sylius_invoicing.filesystem_adapter.invoice%"

sylius_fixtures:
    suites:
        default:
            listeners:
                invoices_purger: ~
