sylius_invoicing_admin:
    resource: "@SyliusInvoicingPlugin/config/routes/admin.yaml"
    prefix: /admin

sylius_invoicing_shop:
    resource: "@SyliusInvoicingPlugin/config/routes/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
